[package]
name = "get_and_return_json"
version = "0.1.0"
authors = ["Band Protocol <dev@bandprotocol.com>"]
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
owasm = { version = "0.1.10" }
obi = { version = "0.0.2" }
lazy_static = "1.4.0"
transpose = "0.2.0"
strum = "0.21"
strum_macros = "0.21"
